/* eslint-disable react-hooks/exhaustive-deps */
import Head from "next/head";
import Banner from "../components/Banner";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import { fetchCoffeeStores } from "../libs/coffeeStores";
import useTrackLocation from "./../hooks/use-track-location";
import { useEffect,useState,useContext } from "react";
import { StoreContext, ACTION_TYPES } from "../context/store-context";

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: { coffeeStores }, // will be passed to the page component as props
  };
}

export default function Home(props) {

  //  const [fetchedcoffeeStores,setCoffeeStores] = useState([])
   const [coffeeStoresError,setCoffeeStoresError] = useState('')

  const { locationErrorMsg, handleTrackLocation, isLocating } =
    useTrackLocation();

    const {dispatch,state} = useContext(StoreContext)
    const {coffeeStores,latLong} = state
   useEffect(()=>{
    const fetchCoffeeStoresByLocation = async () =>{
        try {
          const fetchedCoffeeStores = await fetchCoffeeStores(latLong);
          dispatch({
            type:ACTION_TYPES.SET_COFFEE_STORES,
            payload:{coffeeStores:fetchedCoffeeStores}
          })
           
         } catch (error) {
           console.log({error})
           setCoffeeStoresError(error.message) 
         }
        }
      if(latLong){
        fetchCoffeeStoresByLocation()
      }
   },[latLong])
 
  const handleBannerButtonClick = () => {
    handleTrackLocation();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          bannerButtonText={isLocating ? "Locating..." : "View Stores nearby"}
          handleOnClick={handleBannerButtonClick}
        />

        {locationErrorMsg && <p>Something Went Wrong : {locationErrorMsg}</p>}
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>

        {state.coffeeStores.length > 0 ? (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores Near Me</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((cs) => {
                return (
                  <Card
                    key={cs.fsq_id}
                    href={`/coffee_store/${cs.fsq_id}`}
                    names={cs.name}
                    imageUrl={
                      cs.imageUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    className={styles.Card}
                  />
                );
              })}
            </div>
          </div>
        ):(
          coffeeStoresError ? <h2>{coffeeStoresError}</h2>: <h2>Unable To find Stores Near You</h2>
        )}

        {props.coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((cs) => {
                return (
                  <Card
                    key={cs.fsq_id}
                    href={`/coffee_store/${cs.fsq_id}`}
                    names={cs.name}
                    imageUrl={
                      cs.imageUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    className={styles.Card}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
